// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAevOi8XCo5OAGGvt1XclBDze6D3TSkvKw',
    appId: '1:276285060905:web:58617160d028e7fd2ca938',
    messagingSenderId: '276285060905',
    projectId: 'agri-notification',
    authDomain: 'agri-notification.firebaseapp.com',
    storageBucket: 'agri-notification.appspot.com',
    measurementId: 'G-WHZZB3ZV05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-iar4IF4UpkQ6GkDXTctSZVGc_Oyseg',
    appId: '1:276285060905:android:1617bf6e1075776f2ca938',
    messagingSenderId: '276285060905',
    projectId: 'agri-notification',
    storageBucket: 'agri-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHOW5Fskx0IcAS2aJMdC5g1bPGbSysbqM',
    appId: '1:276285060905:ios:7c85a20a2af460f22ca938',
    messagingSenderId: '276285060905',
    projectId: 'agri-notification',
    storageBucket: 'agri-notification.appspot.com',
    iosBundleId: 'com.argri.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHOW5Fskx0IcAS2aJMdC5g1bPGbSysbqM',
    appId: '1:276285060905:ios:f5f37de30f2d3f0e2ca938',
    messagingSenderId: '276285060905',
    projectId: 'agri-notification',
    storageBucket: 'agri-notification.appspot.com',
    iosBundleId: 'com.argri.mobile.app.agri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAevOi8XCo5OAGGvt1XclBDze6D3TSkvKw',
    appId: '1:276285060905:web:5109e4a76b4714602ca938',
    messagingSenderId: '276285060905',
    projectId: 'agri-notification',
    authDomain: 'agri-notification.firebaseapp.com',
    storageBucket: 'agri-notification.appspot.com',
    measurementId: 'G-31V2RXY7YN',
  );
}
